### ISSUE TITLE
LTS 6.7 and LDAP?

### ISSUE THREAD

**Issue by TomRobinson102** [InfoSec812/sonar-auth-google#11]
I am setting up a new instance of SonarQube 6.7 LTS and have installed the LDAP plugin.  I cannot get it to work.  I have installed open ldap tools and have been able to use ldapsearch to test that I can authenticate from the sonarube machine to the LDAP server.   Any user that attempts to log in to sonarqube gets "Authentication Failed". So how do I go about debugging the LDAP plugin? 

Help!

      - tr -

**Comment by InfoSec812** [comment]
This is a plugin to allow authentication via Google OAuth. It has nothing to do with LDAP.
