### ISSUE TITLE
Callback URL in Security section

### ISSUE THREAD

**Issue by arulrajnet** [InfoSec812/sonar-auth-google#13]
I am using Version 6.7.2 (build 37468) 

![sonar-auth-callback-url](https://user-images.githubusercontent.com/834529/39740328-c54f4886-52b2-11e8-8405-78f4524dc716.png)

In this page showing wrong information as callback url

Refer #3

**Comment by arulrajnet** [comment]
Seems its in this properties file https://github.com/InfoSec812/sonar-auth-google/blob/master/src/main/resources/org/sonar/l10n/authgoogleoauth.properties#L21

**Comment by InfoSec812** [comment]
Not sure what is being asked here.

**Comment by arulrajnet** [comment]
As per #3 the callback url is `${sonarBaseURL}/oauth2/callback/googleoauth` . But In UI of plugin configuration page showing wrong information. Refer screenshot.

**Comment by wisdom41** [comment]
How can I create my own call back url

**Comment by InfoSec812** [comment]
@wisdom41 Please read the notice at the top of the README... This project is no longer maintained or updated.
