### ISSUE TITLE
Documentation has wrong config keys

### ISSUE THREAD

**Issue by drzero42** [InfoSec812/sonar-auth-google#19]
In README.md the config keys are prefixed with sonar.auth.google. However, in the webinterface they are called sonar.auth.googleoauth. If I try to set any env vars (for the Docker Sonarqube image) prefixed with sonar.auth.google, they do nothing. If I use sonar.auth.googleoauth as the prefix, it works fine. It would be great if the documentation could be made to reflect reality :)

**Comment by InfoSec812** [comment]
Resolved by #20
