### ISSUE TITLE
Default Google oauth URL

### ISSUE THREAD

**Issue by ratroncoso** [InfoSec812/sonar-auth-google#3]
My friend,

The plugin sets as default Google authentication URI: https://accounts.googleoauth.com/o/oauth2/auth

It has changed, now it's: https://accounts.google.com/o/oauth2/v2/auth
(*) This can be set in the plugin configuration view in SonarQube

Could you please add to the Readme.md file or to the code to help others?

**Comment by ratroncoso** [comment]
I found another issue.

In the documentation you say we have to authorzize both of the Callback URL, the one from google it's with error, because it says:
${sonarBaseURL}/oauth2/callback/google

And the plugin sends:
${sonarBaseURL}/oauth2/callback/googleoauth

**Comment by InfoSec812** [comment]
Fixed in PR #5
