### ISSUE TITLE
Unable to view "Security" -> "Google"

### ISSUE THREAD

**Issue by gauravk1234** [InfoSec812/sonar-auth-google#7]
Hi,

We have installed SonarQube(version- 5.6.6) and installed plugin - Google Authentication for SonarQube (version 1.6.1) via Update Center. We have restarted SonarQube server but we are not getting "Google" as an option under "Security". We only see the following options under "Security" drop down:
- Users
- Groups
- Global Permissions
- Project Permissions
- Permission Templates

Please suggest if we need to do anything else. Thanks!

**Comment by InfoSec812** [comment]
There would never be a "Google" option under security with this plugin. The settings for configuring Google OAuth are in "Administration -> Configuration -> Security" section...
